---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  gather_facts: false
  tasks:
    
    # - name: install
    #   become: true
    #   ansible.builtin.yum:
    #     name: https://packages.timber.io/vector/0.39.0/vector-0.39.0-1.x86_64.rpm
    #     state: present
    - name: Create a directory if it does not exist
      # become: true
      ansible.builtin.file:
        path: /vector
        state: directory
        mode: 0755
    - name: get_url Vector
      # become: true
      ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
            dest: /vector/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz
    - name: unarchive Vector
      # become: true
      ansible.builtin.unarchive:
        src: /vector/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz
        dest: /vector/
        extra_opts: [--strip-components=2]
        remote_src: yes
    #   tags: rar
    # - name: file Vector
    # - name: template Vector



